name: elder_launcher
description: A launcher focused on simplicity and legibility.

version: 1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  auto_size_text: ^2.1.0
  contacts_service: ^0.3.10
  device_apps: ^1.0.9
  intl: ^0.16.0
  pedantic: ^1.8.0
  permission_handler: ^4.4.0+hotfix.2
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
