name: elder_launcher
description: A launcher focused on simplicity and legibility.

version: 1.3+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  contacts_service: ^0.3.10
  device_apps: ^1.2.0
  intl: ^0.16.1
  pedantic: ^1.9.2
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
